#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ValueConversion.UI.Droid.Resource", IsApplication=true)]

namespace ValueConversion.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::ValueConversion.UI.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::ValueConversion.UI.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::ValueConversion.UI.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::ValueConversion.UI.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::ValueConversion.UI.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::ValueConversion.UI.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::ValueConversion.UI.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::ValueConversion.UI.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::ValueConversion.UI.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::ValueConversion.UI.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::ValueConversion.UI.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::ValueConversion.UI.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::ValueConversion.UI.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::ValueConversion.UI.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::ValueConversion.UI.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::ValueConversion.UI.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::ValueConversion.UI.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::ValueConversion.UI.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::ValueConversion.UI.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::ValueConversion.UI.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::ValueConversion.UI.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxBind = global::ValueConversion.UI.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::ValueConversion.UI.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxGroupItemTemplate = global::ValueConversion.UI.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxItemTemplate = global::ValueConversion.UI.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxLang = global::ValueConversion.UI.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxSource = global::ValueConversion.UI.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxTemplate = global::ValueConversion.UI.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_disclosure = global::ValueConversion.UI.Droid.Resource.Drawable.dialog_disclosure;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_expander_ic_minimized = global::ValueConversion.UI.Droid.Resource.Drawable.dialog_expander_ic_minimized;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_icon = global::ValueConversion.UI.Droid.Resource.Drawable.dialog_icon;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_dark = global::ValueConversion.UI.Droid.Resource.Drawable.dialog_spinner_default_holo_dark;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_light = global::ValueConversion.UI.Droid.Resource.Drawable.dialog_spinner_default_holo_light;
			global::MvvmCross.Dialog.Droid.Resource.Id.MvvmCrossTagId = global::ValueConversion.UI.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Dialog.Droid.Resource.Id.MvxBindingTagUnique = global::ValueConversion.UI.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_BoolField = global::ValueConversion.UI.Droid.Resource.Id.dialog_BoolField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_Button = global::ValueConversion.UI.Droid.Resource.Id.dialog_Button;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_DisclosureField = global::ValueConversion.UI.Droid.Resource.Id.dialog_DisclosureField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_HtmlField = global::ValueConversion.UI.Droid.Resource.Id.dialog_HtmlField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageLeft = global::ValueConversion.UI.Droid.Resource.Id.dialog_ImageLeft;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageRight = global::ValueConversion.UI.Droid.Resource.Id.dialog_ImageRight;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelField = global::ValueConversion.UI.Droid.Resource.Id.dialog_LabelField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelPercentageField = global::ValueConversion.UI.Droid.Resource.Id.dialog_LabelPercentageField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelSubtextField = global::ValueConversion.UI.Droid.Resource.Id.dialog_LabelSubtextField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_Panel = global::ValueConversion.UI.Droid.Resource.Id.dialog_Panel;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_RadioButtonList = global::ValueConversion.UI.Droid.Resource.Id.dialog_RadioButtonList;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_SliderField = global::ValueConversion.UI.Droid.Resource.Id.dialog_SliderField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_Spinner = global::ValueConversion.UI.Droid.Resource.Id.dialog_Spinner;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_ValueField = global::ValueConversion.UI.Droid.Resource.Id.dialog_ValueField;
			global::MvvmCross.Dialog.Droid.Resource.Id.iFormFieldValue = global::ValueConversion.UI.Droid.Resource.Id.iFormFieldValue;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_achievements = global::ValueConversion.UI.Droid.Resource.Layout.dialog_achievements;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldleft = global::ValueConversion.UI.Droid.Resource.Layout.dialog_boolfieldleft;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldright = global::ValueConversion.UI.Droid.Resource.Layout.dialog_boolfieldright;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubleft = global::ValueConversion.UI.Droid.Resource.Layout.dialog_boolfieldsubleft;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubright = global::ValueConversion.UI.Droid.Resource.Layout.dialog_boolfieldsubright;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_button = global::ValueConversion.UI.Droid.Resource.Layout.dialog_button;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_datefield = global::ValueConversion.UI.Droid.Resource.Layout.dialog_datefield;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_fieldsetlabel = global::ValueConversion.UI.Droid.Resource.Layout.dialog_fieldsetlabel;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_floatimage = global::ValueConversion.UI.Droid.Resource.Layout.dialog_floatimage;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_html = global::ValueConversion.UI.Droid.Resource.Layout.dialog_html;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_labeldisclosure = global::ValueConversion.UI.Droid.Resource.Layout.dialog_labeldisclosure;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldbelow = global::ValueConversion.UI.Droid.Resource.Layout.dialog_labelfieldbelow;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldright = global::ValueConversion.UI.Droid.Resource.Layout.dialog_labelfieldright;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_multiline_labelfieldbelow = global::ValueConversion.UI.Droid.Resource.Layout.dialog_multiline_labelfieldbelow;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_onofffieldright = global::ValueConversion.UI.Droid.Resource.Layout.dialog_onofffieldright;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_panel = global::ValueConversion.UI.Droid.Resource.Layout.dialog_panel;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_root = global::ValueConversion.UI.Droid.Resource.Layout.dialog_root;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlist = global::ValueConversion.UI.Droid.Resource.Layout.dialog_selectlist;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlistfield = global::ValueConversion.UI.Droid.Resource.Layout.dialog_selectlistfield;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_textarea = global::ValueConversion.UI.Droid.Resource.Layout.dialog_textarea;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldbelow = global::ValueConversion.UI.Droid.Resource.Layout.dialog_textfieldbelow;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldright = global::ValueConversion.UI.Droid.Resource.Layout.dialog_textfieldright;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding = global::ValueConversion.UI.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding_MvxBind = global::ValueConversion.UI.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding_MvxLang = global::ValueConversion.UI.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxControl = global::ValueConversion.UI.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::ValueConversion.UI.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxExpandableListView = global::ValueConversion.UI.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::ValueConversion.UI.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxImageView = global::ValueConversion.UI.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxImageView_MvxSource = global::ValueConversion.UI.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView = global::ValueConversion.UI.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::ValueConversion.UI.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::ValueConversion.UI.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dialog_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dialog_spinner_default_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dialog_spinner_default_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040011
			public const int MyButton = 2130968593;
			
			// aapt resource value: 0x7f040006
			public const int dialog_BoolField = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int dialog_Button = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int dialog_DisclosureField = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int dialog_HtmlField = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int dialog_ImageLeft = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int dialog_ImageRight = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int dialog_LabelField = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int dialog_LabelPercentageField = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int dialog_LabelSubtextField = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int dialog_Panel = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int dialog_RadioButtonList = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int dialog_SliderField = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int dialog_Spinner = 2130968591;
			
			// aapt resource value: 0x7f040008
			public const int dialog_ValueField = 2130968584;
			
			// aapt resource value: 0x7f040010
			public const int iFormFieldValue = 2130968592;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_html = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labeldisclosure = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_labelfieldbelow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_labelfieldright = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_multiline_labelfieldbelow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_onofffieldright = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_panel = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_root = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_selectlist = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_selectlistfield = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_textarea = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textfieldbelow = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_textfieldright = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Item_MenuItem = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Main = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int View_Colors = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int View_Dates = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int View_Home = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int View_Strings = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int View_TwoWay = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int View_Visibility = 2130903069;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
