// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StarWarsSample.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StarWarsSample.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        public static string Terrain {
            get {
                return ResourceManager.GetString("Terrain", resourceCulture);
            }
        }
        
        public static string Gravity {
            get {
                return ResourceManager.GetString("Gravity", resourceCulture);
            }
        }
        
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        public static string Climate {
            get {
                return ResourceManager.GetString("Climate", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Destroy {
            get {
                return ResourceManager.GetString("Destroy", resourceCulture);
            }
        }
        
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        public static string DeathStarStatus {
            get {
                return ResourceManager.GetString("DeathStarStatus", resourceCulture);
            }
        }
        
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        public static string Targets {
            get {
                return ResourceManager.GetString("Targets", resourceCulture);
            }
        }
        
        public static string AnotherOption {
            get {
                return ResourceManager.GetString("AnotherOption", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string TargetsPlanets {
            get {
                return ResourceManager.GetString("TargetsPlanets", resourceCulture);
            }
        }
        
        public static string TargetsPeople {
            get {
                return ResourceManager.GetString("TargetsPeople", resourceCulture);
            }
        }
    }
}
