#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FragmentSample.UI.Droid.Resource", IsApplication=true)]

namespace FragmentSample.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int MvxSource = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040009
			public const int DialogButton = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int LoadingText = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x01010000
			public const int actualtabcontent = 16842752;
			
			// aapt resource value: 0x7f040004
			public const int detail_fragment = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int list_fragment = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int switchFragmentButton = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int testButton = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int the_notes = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int title_line = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int titles_fragment = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int titles_fragment_holder = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int when_line = 2130968579;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dialog_Names = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment_Detail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment_FirstHeader = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment_List = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_SecondHeader = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_Titles = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItem_SimpleItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Page_DetailView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Page_FormView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Page_HomeView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Page_TabView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Page_TitlesView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SplashScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int tabs_1 = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int tabs_2 = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int tabs_3 = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int tabs_3_big = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
