#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ApiExamples.Droid.Resource", IsApplication=true)]

namespace ApiExamples.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MyButton = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FirstView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Item_Person = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Item_Radio = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Item_Spinner = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Item_SpinnerDropDown = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Item_Test = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SplashScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SubTest_If = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Test_Command = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Test_ContainsSub = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Test_ConvertThis = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Test_Date = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Test_Frame = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Test_If = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Test_LinearLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Test_List = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Test_Maths = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Test_ObservableCollection = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Test_ObservableDictionary = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Test_RadioGroup = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Test_RatingBar = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Test_Relative = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Test_Seek = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Test_Spinner = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Test_Text = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Test_Time = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Test_WithErrors = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
